# https://fshschool.org/docs/sushi/configuration/#exhaustive-example
id: ch.fhir.ig.ch-term
canonical: http://fhir.ch/ig/ch-term
url: http://fhir.ch/ig/ch-term/ImplementationGuide/ch.fhir.ig.ch-term
name: CH_TERM
title: CH Term (R4)
description: Implementation Guide for Swiss Terminologies
status: active
experimental: false
date: 2024-02-08
version: 3.0.0-ci-build
fhirVersion: 4.0.1
copyrightYear: 2019+
releaselabel: ci-build # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
publisher:
  name: HL7 Switzerland
  url: https://www.hl7.ch/
contact:
  - name: HL7 Switzerland
    telecom:
      - system: url
        value: https://www.hl7.ch/
        use: work
license: CC0-1.0
copyright: CC0-1.0
jurisdiction: urn:iso:std:iso:3166#CH

dependencies:
  ihe.formatcode.fhir: 1.1.0
  hl7.terminology: 5.4.0
  
pages:
  index.md:
    title: Home
  terminology.md:
    title: Terminology 
  changelog.md:
    title: Changelog

menu:
  Home: index.html
  Terminology: terminology.html
  Artifacts: artifacts.html
      
# For parameters defined by core FHIR see: 
# http://build.fhir.org/codesystem-guide-parameter-code.html.
# For parameters defined by the FHIR Tools IG  see:
# http://build.fhir.org/ig/FHIR/fhir-tools-ig/branches/master/CodeSystem-ig-parameters.html
parameters:
  excludettl: true
  path-resource:
    - input/resources/codesystem
    - input/resources/conceptmap
    - input/resources/valueset
    - fsh-generated/resources
  allow-extensible-warnings: true
  display-warnings: true  
  special-url:
    - urn:oid:2.16.756.5.30.1.127.3.4
    - urn:oid:2.16.756.5.30.1.127.3.5
    - urn:oid:2.16.756.5.30.1.127.3.6
    - urn:oid:2.16.756.5.30.1.127.3.10.6
    - urn:oid:2.16.756.5.30.1.127.3.10.9
    - urn:oid:2.16.756.5.30.1.127.3.10.10
    - urn:oid:2.16.756.5.30.1.127.3.10.12
    - urn:oid:2.16.756.5.30.1.127.3.10.14
    - urn:oid:2.16.756.5.30.1.127.3.10.18
    - urn:oid:2.16.756.5.30.1.127.3.10.5
    - urn:oid:2.16.756.5.30.1.127.3.10.7
    - urn:oid:0.4.0.127.0.16.1.1.2.1 # edqm-standardterms
    - urn:oid:1.3.6.1.4.1.19376.1.9.2.1 # ihe-pharmaceuticaladvicestatuslist

FSHOnly: false
